from PyQt5 import QtCore, QtGui, QtWidgets
from member import Ui_Member
from client_utils import *

class Ui_Phonebook(object):
    def load_all_member(self, Phonebook, connection):
        self.content = QtWidgets.QWidget(Phonebook)
        self.layout = QtWidgets.QVBoxLayout(self.content)
        self.layout.setSpacing(15)
        self.layout.setAlignment(QtCore.Qt.AlignTop)
        data = ask_phone_book_data(connection)

        receive_thumbnails(connection)

        for item in data:
            s = item['thumbnail']
            s = 'client_data' + s[s.index('/'):]
            item['thumbnail'] = s

            s = item['image']
            s = 'client_data' + s[s.index('/'):]
            item['image'] = s
    
        for item in data:
            add = QtWidgets.QWidget()
            cur = Ui_Member()
            cur.setupUi(add, item, self, connection)
            self.layout.addWidget(add)
        
        self.scrollArea.setWidget(self.content)
        self.bound.layout().addWidget(self.scrollArea)

    # -----------------------------------------------------------

    def setupUi(self, Phonebook, connection):
        Phonebook.setObjectName("Phonebook")
        Phonebook.resize(800, 500)
        Phonebook.setMinimumSize(QtCore.QSize(800, 500))
        Phonebook.setMaximumSize(QtCore.QSize(800, 500))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Phonebook)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.contact_frame = QtWidgets.QFrame(Phonebook)
        self.contact_frame.setMinimumSize(QtCore.QSize(365, 0))
        self.contact_frame.setMaximumSize(QtCore.QSize(365, 16777215))
        self.contact_frame.setStyleSheet("")
        self.contact_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contact_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contact_frame.setObjectName("contact_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.contact_frame)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label01 = QtWidgets.QLabel(self.contact_frame)
        self.label01.setMinimumSize(QtCore.QSize(0, 80))
        self.label01.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.label01.setFont(font)
        self.label01.setStyleSheet("border: 3px solid gray;\n"
"border-radius: 20px;\n"
"background-color: #eeeeee;")
        self.label01.setAlignment(QtCore.Qt.AlignCenter)
        self.label01.setObjectName("label01")
        shadow01 = QtWidgets.QGraphicsDropShadowEffect()
        shadow01.setOffset(0, 0)
        shadow01.setColor(QtGui.QColor(68, 68, 68))
        shadow01.setBlurRadius(15)
        self.label01.setGraphicsEffect(shadow01)
        self.verticalLayout.addWidget(self.label01)
        self.bound = QtWidgets.QFrame(self.contact_frame)
        self.bound.setStyleSheet("QFrame#bound{\n"
"    border: 3px solid gray;\n"
"}")
        self.bound.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bound.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bound.setObjectName("bound")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.bound)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.bound)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 345, 390))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.bound)
        self.horizontalLayout.addWidget(self.contact_frame)
        self.line = QtWidgets.QFrame(Phonebook)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.info_frame = QtWidgets.QFrame(Phonebook)
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.info_frame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.info_frame)
        self.label.setMinimumSize(QtCore.QSize(0, 80))
        self.label.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 3px solid gray;\n"
"border-radius: 20px;\n"
"background-color: #eeeeee;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        shadow02 = QtWidgets.QGraphicsDropShadowEffect()
        shadow02.setOffset(0, 0)
        shadow02.setColor(QtGui.QColor(68, 68, 68))
        shadow02.setBlurRadius(15)
        self.label.setGraphicsEffect(shadow02)
        self.verticalLayout_2.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.info_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QFrame#frame{\n"
"    border: 3px solid gray;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image = QtWidgets.QPushButton(self.frame)
        self.image.setMinimumSize(QtCore.QSize(200, 200))
        self.image.setMaximumSize(QtCore.QSize(200, 200))
        self.image.setStyleSheet("border-radius: 80px;\n"
"background-color: green;")
        self.image.setText("")
        self.image.setIconSize(QtCore.QSize(200, 200))
        self.image.setObjectName("image")
        self.verticalLayout_3.addWidget(self.image, 0, QtCore.Qt.AlignHCenter)
        self.id = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.id.setFont(font)
        self.id.setObjectName("id")
        self.verticalLayout_3.addWidget(self.id)
        self.name = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.verticalLayout_3.addWidget(self.name)
        self.phone_num = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.phone_num.setFont(font)
        self.phone_num.setObjectName("phone_num")
        self.verticalLayout_3.addWidget(self.phone_num)
        self.email = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.verticalLayout_3.addWidget(self.email)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.info_frame)

        self.load_all_member(Phonebook, connection)
        self.retranslateUi(Phonebook)
        QtCore.QMetaObject.connectSlotsByName(Phonebook)
    # -----------------------------------------------------------
    def retranslateUi(self, Phonebook):
        _translate = QtCore.QCoreApplication.translate
        Phonebook.setWindowTitle(_translate("Phonebook", "Phonebook"))
        self.label01.setText(_translate("Phonebook", "Contacts"))
        self.label.setText(_translate("Phonebook", "Info"))
        self.id.setText(_translate("Phonebook", "ID: unknown"))
        self.name.setText(_translate("Phonebook", "Name: unknown"))
        self.phone_num.setText(_translate("Phonebook", "Phone number: unknown"))
        self.email.setText(_translate("Phonebook", "Email: unknown"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Phonebook = QtWidgets.QDialog()
    ui = Ui_Phonebook()
    ui.setupUi(Phonebook)
    Phonebook.show()
    sys.exit(app.exec_())
